version: '3.8'
services:
  emby-controller:
    image: 233bit/emby-controller:latest
    env_file: ./.env
    volumes:
      - ./.env:/app/.env
    ports:
      - "8018:8018"
    networks:
      - default
      - 1panel-network 

networks:
  default:
    driver: bridge
  1panel-network:        
    external: true       
    name: 1panel-network 
